/*Getters Type*/
export const THEME = 'THEME_COLOR'
export const SPINNERCLASS = 'SPINNER_CLASS'
/*Actions Type*/

/*Mutations Type*/
export const ROUTE_CHANGE = 'ROUTE_CHANGE'
export const LOGIN_CHANGE = 'LOGIN_CHANGE'
export const MUSIC_LISTS_CHANGE = 'MUSIC_LISTS_CHANGE'
export const MUSIC_SONG_CHANGE = 'MUSIC_SONG_CHANGE'
export const PLAY_STATE_CHANGE = 'PLAY_STATE_CHANGE'
export const PLAY_TIME_CHANGE = 'PLAY_TIME_CHANGE'
export const DURATION_CHANGE = 'DURATION_CHANGE'
export const PLAY_END_NUM_CHANGE = 'PLAY_END_NUM_CHANGE'
export const LYRIC_DATA_CHANGE = 'LYRIC_DATA_CHANGE'
export const LYRIC_DATA_LINEINDEX_CHANGE = 'LYRIC_DATA_LINEINDEX_CHANGE'
export const LYRIC_DATA_INDEX_CHANGE = 'LYRIC_DATA_INDEX_CHANGE'
